### ISSUE TITLE
something wrong with numbers of languages per country

### ISSUE THREAD

**Issue by nthieberger** [MLR-au/olac-visualisation#3]
Maybe best leave off the numbers of languages per country as they are wrong for a number of examples (UK 59732, Australia 6524, Vanuatu 3220, Vietnam 1625, Wallis and Futuna 103), but it would be good to know how those figures were arrived at.

**Comment by MLR-au** [comment]
ok - trivial to remove.

I've just checked the language archives site and the numbers in the app match those on the site: e.g. http://www.language-archives.org/area/africa

Algeria (102) (language archives) and 102 on the app.

I think this is a label stuff up on my part. The archives site says "The number in parentheses is the number of items cataloged for languages for which the shown country is the primary country." (I must be tired because it's taken me about 4 reads to understand that sentence!).

I'll remove the numbers (trivial to do) in the morning. We can always add them back if required.

**Comment by MLR-au** [comment]
removed
